// routes/reportRoutes.js
// Express Routes For Generating PDF Reports For Evidence And Case Histories

const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const mongoose = require('mongoose');
const path = require('path');

// Models
const Image = require('../models/File');
const CaseLog = require('../models/CaseLog');
const Case = require('../models/Case');
const User = require('../models/User'); 
const isAuthenticated = require('../middleware/auth');

// --- ROUTE 1: SINGLE EVIDENCE REPORT ---
router.get('/generate/:id', isAuthenticated, async (req, res) => {
    try {
        const image = await Image.findById(req.params.id).populate('owner', 'username');
        if (!image) return res.status(404).send("Evidence not found");

        const kase = await Case.findById(image.caseId);
        const canView = (kase.owner.toString() === req.session.userId) || 
                        kase.members.some(m => m.user.toString() === req.session.userId);
        
        if (!canView) return res.status(403).send("Access Denied");

        // 1. LOG THE GENERATION EVENT TO DB
        const userIP = req.ip || req.connection.remoteAddress || 'Unknown';
        await CaseLog.create({
            action: 'File PDF Generated',
            username: req.session.username || 'Unknown',
            ip: userIP,
            caseId: kase._id,
            imageId: image._id,
            fileName: image.originalName,
            details: `PDF Report Generated For File: ${image.originalName || 'Unknown File'}`,
            timestamp: new Date()
        });

        // 2. FETCH LOGS (Now includes the event we just created)
        const logs = await CaseLog.find({ imageId: image._id }).sort({ timestamp: 1 });

        const doc = new PDFDocument({ margin: 40, size: 'A4', bufferPages: true });

        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename="Report_${image.originalName || 'Evidence'}.pdf"`);
        doc.pipe(res);

        const COLOR_RED = '#D9534F';
        const COLOR_DARK = '#333333';
        const COLOR_GREY = '#F4F4F4';

        // HEADER
        doc.rect(0, 0, 600, 30).fill(COLOR_RED);
        doc.fillColor('white').fontSize(10).font('Helvetica-Bold')
           .text('*** LAW ENFORCEMENT SENSITIVE // OFFICIAL USE ONLY ***', 0, 10, { align: 'center' });
        doc.moveDown(3);

        // LOGO
        doc.rect(40, 50, 40, 40).fill(COLOR_DARK);
        doc.fillColor('white').fontSize(24).font('Courier-Bold').text('DV', 47, 58);
        doc.fillColor(COLOR_DARK).fontSize(20).font('Helvetica-Bold').text('DAEMON VAULT', 90, 50);
        doc.fillColor('#666666').fontSize(10).font('Helvetica').text('OPEN SOURCE DIGITAL EVIDENCE MANAGEMENT SYSTEM', 90, 75);

        // META
        doc.fillColor('black').fontSize(9).text(`Report ID: ${new mongoose.Types.ObjectId()}`, 350, 55, { align: 'right' });
        doc.text(`Generated By: ${(req.session.username || 'UNKNOWN').toUpperCase()}`, 350, 68, { align: 'right' });
        doc.text(`Date: ${new Date().toLocaleString()}`, 350, 81, { align: 'right' });

        // METADATA BOX
        doc.moveDown(2);
        doc.rect(40, 120, 515, 130).fill(COLOR_GREY);
        doc.strokeColor('#cccccc').rect(40, 120, 515, 130).stroke();

        doc.fillColor('#007BFF').fontSize(12).font('Helvetica-Bold').text('EVIDENCE METADATA', 55, 135);
        doc.fillColor('black').fontSize(10).font('Helvetica');
        
        let startY = 160;
        doc.font('Helvetica-Bold').text('Filename:', 55, startY);
        doc.font('Helvetica').text(image.originalName || 'Unknown Filename', 120, startY, { width: 170, lineBreak: false, ellipsis: true });
        
        startY += 15;
        doc.font('Helvetica-Bold').text('File Size:', 55, startY);
        doc.font('Helvetica').text(`${((image.size || 0)/1024).toFixed(2)} KB`, 120, startY);

        startY += 15;
        doc.font('Helvetica-Bold').text('Type:', 55, startY);
        doc.font('Helvetica').text(image.mimeType || 'Unknown Type', 120, startY);

        startY = 160;
        doc.font('Helvetica-Bold').text('Case ID:', 300, startY);
        doc.font('Helvetica').text(kase.caseID || 'Unknown Case', 350, startY);

        startY += 15;
        doc.font('Helvetica-Bold').text('File Uploaded By:', 300, startY);
        doc.font('Helvetica').text(image.owner?.username || 'Unknown User', 390, startY);

        startY += 15;
        doc.font('Helvetica-Bold').text('Upload Date:', 300, startY);
        doc.font('Helvetica').text(new Date(image.uploadDate || Date.now()).toLocaleString(), 370, startY);

        startY += 35;
        doc.font('Helvetica-Bold').fillColor(COLOR_RED).text('SHA-256 INTEGRITY HASH:', 55, startY);
        doc.font('Courier').fontSize(8).fillColor('black')
           .text(image.hash || 'Hash Not Available', 55, startY + 15, { width: 490, align: 'left' });

        // TABLE
        doc.moveDown(6); 
        doc.font('Helvetica-Bold').fontSize(14).fillColor(COLOR_DARK).text('CHAIN OF CUSTODY LOG', 40, 290);
        
        const cols = [40, 170, 270, 370, 555];

        const drawRowGrid = (y, h) => {
            doc.strokeColor('black').lineWidth(1);
            doc.rect(cols[0], y, cols[4] - cols[0], h).stroke(); 
            doc.moveTo(cols[1], y).lineTo(cols[1], y + h).stroke();
            doc.moveTo(cols[2], y).lineTo(cols[2], y + h).stroke();
            doc.moveTo(cols[3], y).lineTo(cols[3], y + h).stroke();
        };

        const drawTableHeader = (y) => {
            const h = 20;
            doc.rect(cols[0], y, cols[4] - cols[0], h).fill('#e0e0e0');
            drawRowGrid(y, h);
            doc.fillColor('black').fontSize(9).font('Helvetica-Bold');
            doc.text('TIMESTAMP', cols[0] + 5, y + 6);
            doc.text('ACTION', cols[1] + 5, y + 6);
            doc.text('USER', cols[2] + 5, y + 6);
            doc.text('IP ADDRESS', cols[3] + 5, y + 6);
        };

        let y = 320;
        drawTableHeader(y);
        y += 20; 

        doc.font('Helvetica').fontSize(9);
        
        logs.forEach((log, index) => {
            let detailHeight = 0;
            const detailText = log.details ? `> ${log.details}` : '';

            if (detailText) {
                doc.fontSize(7).font('Courier');
                detailHeight = doc.heightOfString(detailText, { width: 90, align: 'left' });
            }

            let rowHeight = 20;
            if (detailHeight > 0) rowHeight = 20 + detailHeight + 5;

            if (y + rowHeight > 720) {
                doc.addPage();
                y = 50; 
                drawTableHeader(y);
                y += 20;
            }

            if (index % 2 === 0) {
                doc.rect(cols[0], y, cols[4] - cols[0], rowHeight).fill('#f9f9f9');
            }

            drawRowGrid(y, rowHeight);

            const time = new Date(log.timestamp || Date.now()).toLocaleString();
            let actionText = log.action || 'UNKNOWN';

            // --- TEXT CLEANUP ---
            if (actionText === 'CASE_CREATED') actionText = 'Case Created';
            if (actionText === 'CASE_OPENED') actionText = 'Case Opened';
            if (actionText === 'CASE_MEMBER_ADDED') actionText = 'Member Added';
            if (actionText === 'CASE_MEMBER_UPDATED') actionText = 'Member Updated';
            if (actionText === 'CASE_MEMBER_REMOVED') actionText = 'Member Removed';
            
            if (actionText === 'UPLOAD' || actionText === 'FILE_UPLOAD') actionText = 'File Uploaded';
            if (actionText === 'FILE_DELETED') actionText = 'File Deleted';
            if (actionText === 'VERIFY') actionText = 'File Hash Verified';
            if (actionText === 'VIEW') actionText = 'File Viewed';
            
            // NEW: Clean up Report Generation Text
            if (actionText === 'EVIDENCE_REPORT_GENERATED') actionText = 'File PDF Generated';
            if (actionText === 'CASE_REPORT_GENERATED') actionText = 'Case PDF Generated';

            // FORCE BLACK
            doc.fillColor('black').font('Helvetica').fontSize(9);

            doc.text(time, cols[0] + 5, y + 6);
            doc.text(actionText, cols[1] + 5, y + 6, { width: 90, ellipsis: true });
            doc.text(log.username || 'Unknown', cols[2] + 5, y + 6);
            doc.text(log.ip || 'N/A', cols[3] + 5, y + 6);

            if (detailText) {
                doc.fontSize(7).fillColor('#666666').font('Courier')
                   .text(detailText, cols[1] + 5, y + 18, { width: 90, align: 'left' });
                doc.fontSize(9).font('Helvetica'); 
            }

            y += rowHeight;
        });

        const range = doc.bufferedPageRange(); 
        for (let i = range.start; i < range.start + range.count; i++) {
            doc.switchToPage(i); 
            const oldMargins = doc.page.margins;
            doc.page.margins = { top: 0, bottom: 0, left: 0, right: 0 };
            const bottom = doc.page.height - 50;
            doc.rect(0, bottom, doc.page.width, 50).fill(COLOR_DARK);
            doc.fillColor('white').fontSize(8).font('Helvetica')
               .text('CONFIDENTIAL DOCUMENT - PROPERTY OF DAEMON VAULT', 0, bottom + 15, { align: 'center' })
               .text('DO NOT DISTRIBUTE WITHOUT PERMISSION', 0, bottom + 28, { align: 'center' });
            doc.text(`Page ${i + 1} of ${range.count}`, doc.page.width - 150, bottom + 15, { width: 130, align: 'right' });
            doc.page.margins = oldMargins;
        }

        doc.end();

    } catch (err) {
        console.error(err);
        if (!res.headersSent) res.status(500).send("Error generating report");
    }
});

// --- ROUTE 2: FULL CASE HISTORY REPORT ---
router.get('/generate-case/:id', isAuthenticated, async (req, res) => {
    try {
        const kase = await Case.findById(req.params.id);
        if (!kase) return res.status(404).send("Case not found");

        const canView = (kase.owner.toString() === req.session.userId) || 
                        kase.members.some(m => m.user.toString() === req.session.userId);
        
        if (!canView) return res.status(403).send("Access Denied");

        const images = await Image.find({ caseId: kase._id });
        const imageIds = images.map(img => img._id);

        // 1. LOG THE GENERATION EVENT TO DB
        const userIP = req.ip || req.connection.remoteAddress || 'Unknown';
        await CaseLog.create({
            action: 'CASE_REPORT_GENERATED',
            username: req.session.username || 'Unknown',
            ip: userIP,
            caseId: kase._id,
            details: `PDF Report Generated For Case: ${kase.caseID || 'Unknown Case'}`,
            timestamp: new Date()
        });

        // 2. FETCH LOGS (Includes new event)
        const combinedLogs = await CaseLog.find({ 
            $or: [
                { caseId: kase._id },          
                { imageId: { $in: imageIds } } 
            ]
        }).sort({ timestamp: 1 });

        const doc = new PDFDocument({ margin: 40, size: 'A4', bufferPages: true });

        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=CaseReport_${kase.caseID}.pdf`);
        doc.pipe(res);

        const COLOR_RED = '#D9534F';
        const COLOR_DARK = '#333333';
        const COLOR_GREY = '#F4F4F4';

        doc.rect(0, 0, 600, 30).fill(COLOR_RED);
        doc.fillColor('white').fontSize(10).font('Helvetica-Bold')
           .text('*** LAW ENFORCEMENT SENSITIVE // OFFICIAL USE ONLY ***', 0, 10, { align: 'center' });
        doc.moveDown(3);

        doc.rect(40, 50, 40, 40).fill(COLOR_DARK);
        doc.fillColor('white').fontSize(24).font('Courier-Bold').text('DV', 47, 58);
        doc.fillColor(COLOR_DARK).fontSize(20).font('Helvetica-Bold').text('MASTER CASE REPORT', 90, 50);
        doc.fillColor('#666666').fontSize(10).font('Helvetica').text(`FULL AUDIT HISTORY FOR CASE ${kase.caseID}`, 90, 75);

        doc.fillColor('black').fontSize(9).text(`Generated By: ${(req.session.username || 'UNKNOWN').toUpperCase()}`, 350, 55, { align: 'right' });
        doc.text(`Date: ${new Date().toLocaleString()}`, 350, 68, { align: 'right' });

        doc.moveDown(2);
        doc.rect(40, 110, 515, 80).fill(COLOR_GREY);
        doc.strokeColor('#cccccc').rect(40, 110, 515, 80).stroke();

        doc.fillColor('#007BFF').fontSize(12).font('Helvetica-Bold').text('CASE INFORMATION', 55, 125);
        doc.fillColor('black').fontSize(10).font('Helvetica');

        let startY = 145;
        doc.font('Helvetica-Bold').text('Case Name:', 55, startY);
        doc.font('Helvetica').text(kase.name, 125, startY);

        doc.font('Helvetica-Bold').text('Description:', 55, startY + 15);
        doc.font('Helvetica').text(kase.description || 'N/A', 125, startY + 15, { width: 300, ellipsis: true });

        doc.font('Helvetica-Bold').text('Total Evidence:', 400, startY);
        doc.font('Helvetica').text(images.length.toString(), 490, startY);

        doc.moveDown(6);
        const cols = [40, 170, 270, 370, 555];
        
        const drawRowGrid = (y, h) => {
            doc.strokeColor('black').lineWidth(1);
            doc.rect(cols[0], y, cols[4] - cols[0], h).stroke();
            doc.moveTo(cols[1], y).lineTo(cols[1], y + h).stroke();
            doc.moveTo(cols[2], y).lineTo(cols[2], y + h).stroke();
            doc.moveTo(cols[3], y).lineTo(cols[3], y + h).stroke();
        };

        const drawTableHeader = (y) => {
            const h = 20;
            doc.rect(cols[0], y, cols[4] - cols[0], h).fill('#e0e0e0');
            drawRowGrid(y, h);
            doc.fillColor('black').fontSize(9).font('Helvetica-Bold');
            doc.text('TIMESTAMP', cols[0] + 5, y + 6);
            doc.text('ACTION', cols[1] + 5, y + 6);
            doc.text('USER', cols[2] + 5, y + 6);
            doc.text('IP ADDRESS', cols[3] + 5, y + 6);
        };

        let y = 220;
        drawTableHeader(y);
        y += 20;

        doc.font('Helvetica').fontSize(9);

        combinedLogs.forEach((log, index) => {
            let detailHeight = 0;
            const detailText = log.details ? `> ${log.details}` : '';
            if (detailText) {
                doc.fontSize(7).font('Courier');
                detailHeight = doc.heightOfString(detailText, { width: 90, align: 'left' });
            }
            let rowHeight = 20 + (detailHeight > 0 ? detailHeight + 5 : 0);

            if (y + rowHeight > 720) {
                doc.addPage();
                y = 50;
                drawTableHeader(y);
                y += 20;
            }

            if (index % 2 === 0) doc.rect(cols[0], y, cols[4] - cols[0], rowHeight).fill('#f9f9f9');

            drawRowGrid(y, rowHeight);

            const time = new Date(log.timestamp).toLocaleString();
            let actionText = log.action || 'UNKNOWN';

            // --- TEXT CLEANUP ---
            if (actionText === 'CASE_CREATED') actionText = 'Case Created';
            if (actionText === 'CASE_OPENED') actionText = 'Case Opened';
            if (actionText === 'CASE_MEMBER_ADDED') actionText = 'Member Added';
            if (actionText === 'CASE_MEMBER_UPDATED') actionText = 'Member Updated';
            if (actionText === 'CASE_MEMBER_REMOVED') actionText = 'Member Removed';
            
            if (actionText === 'UPLOAD' || actionText === 'FILE_UPLOAD') actionText = 'File Uploaded';
            if (actionText === 'FILE_DELETED') actionText = 'File Deleted';
            if (actionText === 'VERIFY') actionText = 'File Hash Verified';
            if (actionText === 'VIEW') actionText = 'File Viewed';

            // NEW: Clean up Report Generation Text
            if (actionText === 'EVIDENCE_REPORT_GENERATED') actionText = 'File PDF Generated';
            if (actionText === 'CASE_REPORT_GENERATED') actionText = 'Case PDF Generated';

            // FORCE BLACK TEXT
            doc.fillColor('black').font('Helvetica').fontSize(9);

            doc.text(time, cols[0] + 5, y + 6);
            doc.text(actionText, cols[1] + 5, y + 6, { width: 90, ellipsis: true });
            doc.text(log.username || 'Unknown', cols[2] + 5, y + 6);
            doc.text(log.ip || 'N/A', cols[3] + 5, y + 6);

            if (detailText) {
                doc.fontSize(7).fillColor('#666666').font('Courier')
                   .text(detailText, cols[1] + 5, y + 18, { width: 90, align: 'left' });
                doc.fontSize(9);
            }
            y += rowHeight;
        });

        const range = doc.bufferedPageRange();
        for (let i = range.start; i < range.start + range.count; i++) {
            doc.switchToPage(i);
            const oldMargins = doc.page.margins;
            doc.page.margins = { top: 0, bottom: 0, left: 0, right: 0 };
            const bottom = doc.page.height - 50;

            doc.rect(0, bottom, doc.page.width, 50).fill(COLOR_DARK);
            doc.fillColor('white').fontSize(8).font('Helvetica')
               .text('CONFIDENTIAL DOCUMENT - PROPERTY OF DAEMON VAULT', 0, bottom + 15, { align: 'center' })
               .text('DO NOT DISTRIBUTE WITHOUT PERMISSION', 0, bottom + 28, { align: 'center' });
            doc.text(`Page ${i + 1} of ${range.count}`, doc.page.width - 150, bottom + 15, { width: 130, align: 'right' });

            doc.page.margins = oldMargins;
        }

        doc.end();

    } catch (err) {
        console.error(err);
        res.status(500).send("Error generating case report");
    }
});

module.exports = router;